# Generated by Django 2.2.28 on 2023-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_usage',
        ),
        migrations.AddField(
            model_name='user',
            name='days_filter',
            field=models.PositiveIntegerField(blank=True, default=30),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
