# Generated by Django 2.2.28 on 2026-04-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conference_unique_conference_id_app'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('conference_id', 'app')},
        ),
    ]
